export const employsIn = [
  {
    id: 1,
    img: "/Avatar.png",
    name: "Ash Lowe",
    email: "tanya.hill@example.com",
  },
  {
    id: 2,
    img: "/Avatar2.png",
    name: "Katie Poole",
    email: "michael.mitc@example.com",
  },
  {
    id: 3,
    img: "/Avatar3.png",
    name: "Charlie Gray",
    email: "kenzi.lawson@example.com",
  },
  {
    id: 4,
    img: "/Avatar4.png",
    name: "Nicholas Matthews",
    email: "debbie.baker@example.com",
  },
  {
    id: 5,
    img: "/Avatar5.png",
    name: "Carmen Ewing",
    email: "georgia.young@example.com",
  },
  {
    id: 6,
    img: "/Avatar6.png",
    name: "Millie Jones",
    email: "dolores.chambers@example.com",
  },
  {
    id: 7,
    img: "/Avatar7.png",
    name: "Eloise Robinson",
    email: "deanna.curtis@example.com",
  },
  {
    id: 8,
    img: "/Avatar8.png",
    name: "Monroe Benjamin",
    email: "sara.cruz@example.com",
  },
];

export const employsBreak = [
  {
    id: 5,
    img: "/Avatar5.png",
    name: "Carmen Ewing",
    email: "georgia.young@example.com",
  },
  {
    id: 6,
    img: "/Avatar6.png",
    name: "Millie Jones",
    email: "dolores.chambers@example.com",
  },
];

export const employsOut = [
  {
    id: 4,
    img: "/Avatar4.png",
    name: "Nicholas Matthews",
    email: "debbie.baker@example.com",
  },
  {
    id: 5,
    img: "/Avatar5.png",
    name: "Carmen Ewing",
    email: "georgia.young@example.com",
  },
  {
    id: 6,
    img: "/Avatar6.png",
    name: "Millie Jones",
    email: "dolores.chambers@example.com",
  },
  {
    id: 7,
    img: "/Avatar7.png",
    name: "Eloise Robinson",
    email: "deanna.curtis@example.com",
  },
  {
    id: 8,
    img: "/Avatar8.png",
    name: "Monroe Benjamin",
    email: "sara.cruz@example.com",
  },
];

export const bestSellingProducts = [
  {
    id: 1,
    item: "Doxacurium",
    price: 156.29,
    sold: 300,
    img: "/bestSellingItem1.png",
  },
  {
    id: 2,
    item: "Cisatracurium",
    price: 135.95,
    sold: 200,
    img: "/bestSellingItem2.png",
  },
  {
    id: 3,
    item: "Decamethonium",
    price: 145.63,
    sold: 150,
    img: "/bestSellingItem3.png",
  },
  {
    id: 4,
    item: "Decamethonium",
    price: 168.72,
    sold: 100,
    img: "/bestSellingItem4.png",
  },
  {
    id: 5,
    item: "Vecuronium",
    price: 168.72,
    sold: 100,
    img: "/bestSellingItem5.png",
  },
  {
    id: 6,
    item: "Vecuronium",
    price: 168.72,
    sold: 100,
    img: "/bestSellingItem6.png",
  },
  {
    id: 7,
    item: "Vecuronium",
    price: 168.72,
    sold: 100,
    img: "/bestSellingItem7.png",
  },
  {
    id: 8,
    item: "Mivacurium",
    price: 104.61,
    sold: 50,
    img: "/bestSellingItem8.png",
  },
  {
    id: 9,
    item: "Mivacurium",
    price: 104.61,
    sold: 50,
    img: "/bestSellingItem9.png",
  },
  {
    id: 10,
    item: "Mivacurium",
    price: 104.61,
    sold: 50,
    img: "/bestSellingItem10.png",
  },
  {
    id: 11,
    item: "Mivacurium",
    price: 104.61,
    sold: 50,
    img: "/bestSellingItem11.png",
  },
  {
    id: 12,
    item: "Mivacurium",
    price: 104.61,
    sold: 50,
    img: "/bestSellingItem11.png",
  },
];

export const orders = [
  {
    name: "Jan",
    orders: 2400,
    amt: 2400,
  },
  {
    name: "Feb",
    orders: 1398,
    amt: 2210,
  },
  {
    name: "Mar",
    orders: 9800,
    amt: 2290,
  },
  {
    name: "Apr",
    orders: 3908,
    amt: 2000,
  },
  {
    name: "May",
    orders: 4800,
    amt: 2181,
  },
  {
    name: "June",
    orders: 3800,
    amt: 2500,
  },
  {
    name: "Jul",
    orders: 4300,
    amt: 2100,
  },
  {
    name: "Aug",
    orders: 9800,
    amt: 2290,
  },
  {
    name: "Sep",
    orders: 3908,
    amt: 2000,
  },
  {
    name: "Oct",
    orders: 4800,
    amt: 2181,
  },
  {
    name: "Nov",
    orders: 3800,
    amt: 2500,
  },
  {
    name: "Dec",
    orders: 4300,
    amt: 2100,
  },
];

export const products = [
  {
    id: 1,
    img: "/productListIcon.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Kitchen",
    stock: 43,
    price: 20,
  },
  {
    id: 2,
    img: "/productListIcon2.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Kitchen",
    stock: 0,
    price: 50,
  },
  {
    id: 3,
    img: "/productListIcon3.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Bath",
    stock: 30,
    price: 14,
  },
  {
    id: 4,
    img: "/productListIcon4.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Bath",
    stock: 10,
    price: 13,
  },
  {
    id: 5,
    img: "/productListIcon5.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Bath",
    stock: 50,
    price: 19,
  },
  {
    id: 6,
    img: "/productListIcon6.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Bath",
    stock: 39,
    price: 654,
  },
  {
    id: 7,
    img: "/productListIcon7.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Kitchen",
    stock: 65,
    price: 70,
  },
  {
    id: 8,
    img: "/productListIcon8.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Kitchen",
    stock: 2,
    price: 65,
  },
  {
    id: 9,
    img: "/productListIcon9.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Bath",
    stock: 2,
    price: 65,
  },
  {
    id: 10,
    img: "/productListIcon10.png",
    name: "Tanner Finsha",
    product_id: "#23454GH6J7YT6",
    category: "Kitchen",
    stock: 2,
    price: 65,
  },
];
